site_name: Event Explorer
site_url: https://<your-user>.github.io/<repo>   # adjust after first push

nav:
  - Home: index.md

theme:
  name: null            # disable stock themes
  custom_dir: theme     # pick up our custom templates

# Bring in the extra assets
extra_css:
  - css/style.css
extra_javascript:
  # React + tooling from fast CDNs
  - https://unpkg.com/react@18/umd/react.production.min.js
  - https://unpkg.com/react-dom@18/umd/react-dom.production.min.js
  - https://unpkg.com/babel-standalone@6/babel.min.js
  - https://cdn.jsdelivr.net/npm/js-yaml@4/dist/js-yaml.min.js
  - js/app.jsx          # our React code (transpiled in-browser by Babel)

plugins:
  - search              # still get full-site MkDocs search
  - macros
